spring:
  application:
    name: back
  datasource:
    url: jdbc:mysql://10.0.0.158:3306/qiuqiu
    username: root
    password: Zhimeilideni990
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

server:
  port: 8888

jwt:
  expiration: 8640000
  secret: radioastronomical6zgadjnmaowjdoiaajoida
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true  # 支持通过 Mapper 接口的方法参数来传递分页参数
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ztf.back.model.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      ztf:
        back:
          mapper: debug

