spring:
  application:
    name: back
  datasource:
    url: jdbc:mysql://10.0.0.158:3306/qiuqiu
    username: root
    password: Zhimeilideni990
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

server:
  port: 8888

jwt:
  expiration: 8640000
  secret: adjioadioajdoiatr6zgadjnmaowjdoiaajoida

logging:
  level:
    com.zaxxer.hikari: WARN
    org.springframework.jdbc.datasource: WARN
    org.springframework.boot.autoconfigure.jdbc.DataSourceInitializer: WARN